AWSTemplateFormatVersion: '2010-09-09'
Description: 'Debug S3 bucket only'

Parameters:
  ProjectName:
    Type: String
    Default: debug
  Environment:
    Type: String
    Default: production

Resources:
  # S3 Bucket for Static Assets
  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Environment}-assets-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref StaticAssetsBucket
    Export:
      Name: !Sub "${ProjectName}-${Environment}-S3BucketName"